spring:
    data:
      mongodb:
             host: ${MONGO_URL:localhost}
             port: ${MONGO_PORT:27017}
             database: ${MONGO_DATABASE:admin}
    minio:
         urlMinio: http://${MINIO_URL:localhost}:${MINIO_PORT:9080}
         accessKey: ${MINIO_ACCESS_KEY:rootroot}
         secretKey: ${MINIO_SECRET_KEY:rootroot}
